#!/usr/bin/env python3
"""
Module containing the WGAN_GP class implementation for Wasserstein GANs with
Gradient Penalty, updated with weight loading capabilities.
"""

import tensorflow as tf
from tensorflow import keras


class WGAN_GP(keras.Model):
    """
    Wasserstein GAN model class with Gradient Penalty inheriting from
    keras.Model.
    """

    def __init__(self, generator, discriminator, latent_generator,
                 real_examples, batch_size=200, disc_iter=2,
                 learning_rate=.005, lambda_gp=10):
        """
        Initializes the WGAN_GP model.

        Parameters:
            generator: Keras model representing the generator network.
            discriminator: Keras model representing the discriminator network.
            latent_generator: Function generating latent noise vectors.
            real_examples: Tensor of real example samples.
            batch_size: Integer, size of mini-batches used in training.
            disc_iter: Integer, discriminator steps per generator step.
            learning_rate: Float, learning rate for Adam optimizer.
            lambda_gp: Weight coefficient for gradient penalty.
        """
        super().__init__()
        self.latent_generator = latent_generator
        self.real_examples = real_examples
        self.generator = generator
        self.discriminator = discriminator
        self.batch_size = batch_size
        self.disc_iter = disc_iter

        self.learning_rate = learning_rate
        self.beta_1 = .3
        self.beta_2 = .9

        self.lambda_gp = lambda_gp
        self.dims = self.real_examples.shape
        self.len_dims = tf.size(self.dims)
        self.axis = tf.range(1, self.len_dims, delta=1, dtype='int32')
        self.scal_shape = self.dims.as_list()
        self.scal_shape[0] = self.batch_size
        for i in range(1, self.len_dims):
            self.scal_shape[i] = 1
        self.scal_shape = tf.convert_to_tensor(self.scal_shape)

        # Define the generator loss and optimizer:
        self.generator.loss = lambda x: -tf.math.reduce_mean(x)
        self.generator.optimizer = keras.optimizers.Adam(
            learning_rate=self.learning_rate,
            beta_1=self.beta_1,
            beta_2=self.beta_2
        )
        self.generator.compile(
            optimizer=generator.optimizer, loss=generator.loss
        )

        # Define the discriminator loss and optimizer:
        self.discriminator.loss = (
            lambda x, y: tf.math.reduce_mean(x) - tf.math.reduce_mean(y)
        )
        self.discriminator.optimizer = keras.optimizers.Adam(
            learning_rate=self.learning_rate,
            beta_1=self.beta_1,
            beta_2=self.beta_2
        )
        self.discriminator.compile(
            optimizer=discriminator.optimizer, loss=discriminator.loss
        )

    def get_fake_sample(self, size=None, training=False):
        """
        Generates a sample of fake data using the generator network.

        Parameters:
            size: Integer, number of fake samples to generate.
            training: Boolean, whether the call is for training.

        Returns:
            Tensor of fake samples generated by the generator.
        """
        if not size:
            size = self.batch_size
        return self.generator(self.latent_generator(size), training=training)

    def get_real_sample(self, size=None):
        """
        Retrieves a random sample of real data from real_examples.

        Parameters:
            size: Integer, number of real samples to retrieve.

        Returns:
            Tensor containing a random subset of real examples.
        """
        if not size:
            size = self.batch_size
        sorted_indices = tf.range(tf.shape(self.real_examples)[0])
        random_indices = tf.random.shuffle(sorted_indices)[:size]
        return tf.gather(self.real_examples, random_indices)

    def get_interpolated_sample(self, real_sample, fake_sample):
        """
        Generates interpolations between real and fake samples.

        Parameters:
            real_sample: Tensor of real samples.
            fake_sample: Tensor of generated fake samples.

        Returns:
            Tensor of interpolated samples.
        """
        u = tf.random.uniform(self.scal_shape)
        v = tf.ones(self.scal_shape) - u
        return u * real_sample + v * fake_sample

    def gradient_penalty(self, interpolated_sample):
        """
        Computes the gradient penalty for WGAN-GP.

        Parameters:
            interpolated_sample: Interpolated images tensor.

        Returns:
            Tensor scalar representing the gradient penalty.
        """
        with tf.GradientTape() as gp_tape:
            gp_tape.watch(interpolated_sample)
            pred = self.discriminator(interpolated_sample, training=True)
        grads = gp_tape.gradient(pred, [interpolated_sample])[0]
        norm = tf.sqrt(tf.reduce_sum(tf.square(grads), axis=self.axis))
        return tf.reduce_mean((norm - 1.0) ** 2)

    def replace_weights(self, gen_h5, disc_h5):
        """
        Replaces generator and discriminator weights with pre-trained weights.

        Parameters:
            gen_h5: Path to the .h5 file containing generator weights.
            disc_h5: Path to the .h5 file containing discriminator weights.
        """
        self.generator.load_weights(gen_h5)
        self.discriminator.load_weights(disc_h5)

    def train_step(self, useless_argument):
        """
        Executes a single training step for WGAN-GP.

        Parameters:
            useless_argument: Unused input required by Keras Model.fit
                protocol.

        Returns:
            Dictionary containing 'discr_loss', 'gen_loss', and 'gp'.
        """
        for _ in range(self.disc_iter):
            with tf.GradientTape() as tape:
                real_samples = self.get_real_sample()
                fake_samples = self.get_fake_sample(training=True)
                interpolated_samples = self.get_interpolated_sample(
                    real_samples, fake_samples
                )

                pred_real = self.discriminator(real_samples, training=True)
                pred_fake = self.discriminator(fake_samples, training=True)

                discr_loss = self.discriminator.loss(pred_fake, pred_real)
                gp = self.gradient_penalty(interpolated_samples)
                new_discr_loss = discr_loss + self.lambda_gp * gp

            gradients = tape.gradient(
                new_discr_loss, self.discriminator.trainable_variables
            )
            self.discriminator.optimizer.apply_gradients(
                zip(gradients, self.discriminator.trainable_variables)
            )

        with tf.GradientTape() as tape:
            fake_samples = self.get_fake_sample(training=True)
            pred_fake = self.discriminator(fake_samples, training=True)
            gen_loss = self.generator.loss(pred_fake)

        gradients = tape.gradient(
            gen_loss, self.generator.trainable_variables
        )
        self.generator.optimizer.apply_gradients(
            zip(gradients, self.generator.trainable_variables)
        )

        return {"discr_loss": discr_loss, "gen_loss": gen_loss, "gp": gp}
